on:
  pull_request:
    branches:
      - main

jobs:
  app_checks:
    name: Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Pull docker-compose
        run: docker-compose -f docker-compose.yml pull
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: copy .env.example to .env for testing
        run: cp -n .env.example .env
      - name: Prepare containers
        run: make start && make composer-install
      - name: Run coding style check
        run: make code-style-check
      - name: Run tests
        run: make tests